language: node_js
node_js:
  - "stable"
cache:
  directories:
  - /frontend/node_modules
script:
  - cd frontend
  - npm run dev
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: branch-3