language: python
node_js:
  - "stable"
cache:
  directories:
  - /frontend/node_modules
script:
  - cd frontend
  - npm install webpack
  - npm install -D webpack-cli
  - npm run build
  - cd ..
  - cd backend
  - py manage.py runserver
deploy:
  provider: heroku
  api_key: $api_key
  app: turners-redesign
  local_dir: backend/TurnersRedesign/static/build
  on:
    branch: branch-3