language: python
node_js:
  - "stable"
python:
  - "3.9.0"
cache:
  directories:
  - /frontend/node_modules

install: 
  - pip install Django
script:
  
  - cd backend
  - python3 manage.py runserver 0.0.0.0:8000
deploy:
  provider: heroku
  api_key: $api_key
  app: turners-redesign
  on:
    branch: branch-3